local oldsignal = {} -- Буферная таблица  предыдущего состояния входов
local signals = {}
local source_aps ={  -- Оописание технологического объекта
    a="КЦ",
    b="АВО",
    c="ПК",
    d="УПТПГ",
    e="УП",
    f="ГПА",
	g="СОДУ",
	r="САР"
}

local event_aps ={  -- Таблица типов событий
    a=10000,  -- Аварии
    w=10100,  -- Предупреждения
    s=102,    -- Телесигнализация
    c=100,    -- Команды
	r=9998    -- САР КЦ
}

local function Add_Event (Arg)-- Функция добавления события. Arg - массив!!! передаваемых параметров
    --local signal = Core[Arg[1]]
	--Core.addLogMsg(signals[Arg[1]].text..'|||'..signals[Arg[1]].class..'|||'..tostring(signal)..'|||'..signals[Arg[1]].src)
    Core.addEvent(signals[Arg[1]].text,  -- Текст события
                  signals[Arg[1]].class, -- Класс события
                  Arg[2] and 1 or 0,     -- Признак события (появление/пропадание)
                  signals[Arg[1]].src,   -- Источник события
				  '',					 -- Пользователь
				  Arg[1])				 -- ID  
end


signals = {
--Обрыв аналоговых входов
['SHKU17_A1_APS.Tnv_obriv']	=	{text =  'Обрыв канал - Температура наружного воздуха',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tgr_obriv']	=	{text =  'Обрыв канал - Температура грунта',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1kr7B_obriv']	=	{text =  'Обрыв канал - Температура газа до крана 7Б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2kr8B_obriv']	=	{text =  'Обрыв канал - Температура газа после крана 8Б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1kr8Bbis_obriv']	=	{text =  'Обрыв канал - Температура газа до крана 8Ббис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2kr8Bbis_obriv']	=	{text =  'Обрыв канал - Температура газа после крана 8Ббис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2kr8Bbis_obriv']	=	{text =  'Обрыв канал - Давление газа после крана 8Ббис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg1kr7B_obriv']	=	{text =  'Обрыв канал - Давление газа до крана 7Б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_01_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Patm_obriv']	=	{text =  'Обрыв канал - Давление атмосферного воздуха',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.PozAPK3_obriv']	=	{text =  'Обрыв канал - Положение АПК №3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_02_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_03_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_04_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_05_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24VTI1_obriv']	=	{text =  'Обрыв канал - Контроль 24 В ТИ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1PU_obriv']	=	{text =  'Обрыв канал - Температура газа  до  ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2PU_obriv']	=	{text =  'Обрыв канал - Температура газа  после ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_06_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg1PU_obriv']	=	{text =  'Обрыв канал - Давление газа  до  ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2PU_obriv']	=	{text =  'Обрыв канал - Давление газа  после ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_07_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1gr_2_obriv']	=	{text =  'Обрыв канал - Температура газа на входе  группы 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2gr_2_obriv']	=	{text =  'Обрыв канал - Температура газа на выходе  группы 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2plum_obriv']	=	{text =  'Обрыв канал - Давление газа на выходном шлейфе  ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_08_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pcompr_v_obriv']	=	{text =  'Обрыв канал - Давление сжатого воздуха',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ttg_obriv']	=	{text =  'Обрыв канал - Температура топливного газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tpg_obriv']	=	{text =  'Обрыв канал - Температура пускового газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ptg_obriv']	=	{text =  'Обрыв канал - Давление топливного  газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ppg_obriv']	=	{text =  'Обрыв канал - Давление пускового газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24VTI2_obriv']	=	{text =  'Обрыв канал - Контроль 24 В ТИ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe1_obriv']	=	{text =  'Обрыв канал - Уровень в пожарной емкости №1',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe2_obriv']	=	{text =  'Обрыв канал - Уровень в пожарной емкости №2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe3_obriv']	=	{text =  'Обрыв канал - Уровень в пожарной емкости №3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe7_obriv']	=	{text =  'Обрыв канал - Уровень в пожарной емкости №7',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe8_obriv']	=	{text =  'Обрыв канал - Уровень в пожарной емкости №8',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tozh_obriv']	=	{text =  'Обрыв канал - Температура охлаждающей жидкости',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_09_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_10_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_11_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_12_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_13_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_14_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_15_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_16_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_17_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24VTI3_obriv']	=	{text =  'Обрыв канал - Контроль 24 В ТИ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_18_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_19_obriv']	=	{text =  'Обрыв канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Uosn_p_SHKU17_obriv']	=	{text =  'Обрыв канал - Напряжение основного питания ШКУ-17',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Urez_p_SHKU17_obriv']	=	{text =  'Обрыв канал - Напряжение резервного питания ШКУ-17',		src = source_aps.e, class = event_aps.w},

--К.З. аналоговых входов
['SHKU17_A1_APS.Tnv_kz']	=	{text =  'КЗ канал - Температура наружного воздуха',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tgr_kz']	=	{text =  'КЗ канал - Температура грунта',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1kr7B_kz']	=	{text =  'КЗ канал - Температура газа до крана 7Б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2kr8B_kz']	=	{text =  'КЗ канал - Температура газа после крана 8Б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1kr8Bbis_kz']	=	{text =  'КЗ канал - Температура газа до крана 8Ббис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2kr8Bbis_kz']	=	{text =  'КЗ канал - Температура газа после крана 8Ббис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2kr8Bbis_kz']	=	{text =  'КЗ канал - Давление газа после крана 8Ббис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg1kr7B_kz']	=	{text =  'КЗ канал - Давление газа до крана 7Б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_01_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Patm_kz']	=	{text =  'КЗ канал - Давление атмосферного воздуха',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.PozAPK3_kz']	=	{text =  'КЗ канал - Положение АПК №3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_02_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_03_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_04_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_05_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24VTI1_kz']	=	{text =  'КЗ канал - Контроль 24 В ТИ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1PU_kz']	=	{text =  'КЗ канал - Температура газа  до  ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2PU_kz']	=	{text =  'КЗ канал - Температура газа  после ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_06_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg1PU_kz']	=	{text =  'КЗ канал - Давление газа  до  ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2PU_kz']	=	{text =  'КЗ канал - Давление газа  после ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_07_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg1gr_2_kz']	=	{text =  'КЗ канал - Температура газа на входе  группы 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tg2gr_2_kz']	=	{text =  'КЗ канал - Температура газа на выходе  группы 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2plum_kz']	=	{text =  'КЗ канал - Давление газа на выходном шлейфе  ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_08_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pcompr_v_kz']	=	{text =  'КЗ канал - Давление сжатого воздуха',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ttg_kz']	=	{text =  'КЗ канал - Температура топливного газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tpg_kz']	=	{text =  'КЗ канал - Температура пускового газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ptg_kz']	=	{text =  'КЗ канал - Давление топливного  газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ppg_kz']	=	{text =  'КЗ канал - Давление пускового газа',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24VTI2_kz']	=	{text =  'КЗ канал - Контроль 24 В ТИ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe1_kz']	=	{text =  'КЗ канал - Уровень в пожарной емкости №1',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe2_kz']	=	{text =  'КЗ канал - Уровень в пожарной емкости №2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe3_kz']	=	{text =  'КЗ канал - Уровень в пожарной емкости №3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe7_kz']	=	{text =  'КЗ канал - Уровень в пожарной емкости №7',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Lpe8_kz']	=	{text =  'КЗ канал - Уровень в пожарной емкости №8',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Tozh_kz']	=	{text =  'КЗ канал - Температура охлаждающей жидкости',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_09_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_10_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_11_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_12_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_13_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_14_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_15_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_16_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_17_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24VTI3_kz']	=	{text =  'КЗ канал - Контроль 24 В ТИ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_18_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_19_kz']	=	{text =  'КЗ канал - Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Uosn_p_SHKU17_kz']	=	{text =  'КЗ канал - Напряжение основного питания ШКУ-17',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Urez_p_SHKU17_kz']	=	{text =  'КЗ канал - Напряжение резервного питания ШКУ-17',		src = source_aps.e, class = event_aps.w},

--Ошибки модулей Сонет
['SERVER_APS.SHKU17_A1_3']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_3',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_4']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_4',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_5']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_5',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_6']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_6',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_7']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_7',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_8']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_8',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_9']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_9',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A1_10']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A1_10',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_3']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_3',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_4']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_4',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_5']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_5',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_6']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_6',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_7']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_7',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_8']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_8',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_9']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_9',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A2_10']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A2_10',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_3']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_3',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_4']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_4',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_5']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_5',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_6']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_6',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_7']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_7',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_8']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_8',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_9']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_9',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A3_10']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A3_10',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_3']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_3',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_4']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_4',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_5']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_5',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_6']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_6',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_7']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_7',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_8']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_8',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_9']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_9',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A4_10']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A4_10',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_3']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_3',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_4']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_4',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_5']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_5',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_6']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_6',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_7']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_7',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_8']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_8',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_9']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_9',		src = source_aps.e, class = event_aps.w},
['SERVER_APS.SHKU17_A5_10']	=	{text =  'ШКУ-17. Ошибка модуля Сонет: A5_10',		src = source_aps.e, class = event_aps.w},

--АПС по дискретным входам
['SHKU17_A1_APS.Ala_ispr_Ppr']	=	{text =  'Неисправность питания преобразователей',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_01']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_02']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_03']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_04']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_05']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2_plum']	=	{text =  'Давление газа на выходном шлейфе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.No_U_AVVgr_3']	=	{text =  'Отсутствие напряжения в схеме аварийно-вытяжных вентиляторов группы 3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.no_U_PV5']	=	{text =  'Отсутствие напряжения в схеме приточного вентилятора №5',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.no_U_PV6']	=	{text =  'Отсутствие напряжения в схеме приточного вентилятора №6',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Inc1_ON']	=	{text =  'Ввод №1 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Inc1_OFF']	=	{text =  'Ввод №1 отлючен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Inc2_ON']	=	{text =  'Ввод №2 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Inc2_OFF']	=	{text =  'Ввод №2 отлючен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.SS_ON']	=	{text =  'Секционный выключатель включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.SS_OFF']	=	{text =  'Секционный выключатель отлючен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.APK_ON']	=	{text =  'АПК открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.APK_OFF']	=	{text =  'АПК закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.APK_Heat_ON']	=	{text =  'АПК обогрев включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.N11GD100_1_WORK']	=	{text =  '11ГД-100 №1 в работе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.N11GD100_1_FLT']	=	{text =  'Авария 11ГД-100 №1',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.N11GD100_2_WORK']	=	{text =  '11ГД-100 №2 в работе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.N11GD100_2_FLT']	=	{text =  'Авария 11ГД-100 №2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.AC804_FLT']	=	{text =  'АС-804 неисправна',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.AC804_WORK']	=	{text =  'АС-804 в работе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.AC804_REZ']	=	{text =  'АС-804 в резерве',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.TG2_FLT']	=	{text =  'Авария теплогенератора №2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.P3_30_ON']	=	{text =  'Насос РЗ-30 ГСМ включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.P3_30_KVR_AUTO']	=	{text =  'КВР насоса РЗ-30 ГСМ в положении автомат',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_06']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.rez_07']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ctrl24_TC_1']	=	{text =  'Контроль 24 В ТС №1',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Fire1GN_KC2']	=	{text =  'Пожар в ГН КЦ 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Fire1mb_KC2']	=	{text =  'Пожар в маслобаке КЦ 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Fire1_AC804']	=	{text =  'Пожар в АС-804',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Fire1_ESSN']	=	{text =  'Пожар в ЭССН',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Fire1_RU04']	=	{text =  'Пожар РУ-0,4 кВ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Fire1_Kot']	=	{text =  'Пожар в котельной',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag1_GN_KC2_10p']	=	{text =  'Загазованность в ГН КЦ 2 10%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag1_GN_KC2_20p']	=	{text =  'Загазованность в ГН КЦ 2 20%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag1_PU_KC2_10p']	=	{text =  'Загазованность в ПУ КЦ 2 10%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag1_PU_KC2_20p']	=	{text =  'Загазованность в ПУ КЦ 2  20%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag1_MZ_ESSN_10p']	=	{text =  'Загазованность в машзале ЭССН 10%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag1_MZ_ESSN_20p']	=	{text =  'Загазованность в машзале ЭССН  20%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag_CH4_KOT_10p']	=	{text =  'Загазованность СН4  в котельной  10%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag_CH4_KOT_20p']	=	{text =  'Загазованность СН4  в котельной 20%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag_CO_KOT_20mg']	=	{text =  'Загазованность СО в котельной 20мг/м3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Zag_CO_KOT_100mg']	=	{text =  'Загазованность СО в котельной 100мг/м3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Neispr_SPO_KZ']	=	{text =  'Неисправность системы ПО и КЗ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.ComSh_AC804_inc1_Q1_ON']	=	{text =  'Щит связи АС-804. Ввод №1: контактор №1 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.ComSh_AC804_inc1_Q1_OFF']	=	{text =  'Щит связи АС-804. Ввод №1: контактор №1 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.ComSh_AC804_inc2_Q2_ON']	=	{text =  'Щит связи АС-804. Ввод №2: контактор №2 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.ComSh_AC804_inc2_Q2_OFF']	=	{text =  'Щит связи АС-804. Ввод №2: контактор №2 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Call_KC2']	=	{text =  'Вызов в цех №2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_08']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ala_KOT']	=	{text =  'Авария в котельной',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_ON']	=	{text =  'Периметральное освещение КЦ 2 включено',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_09']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_10']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_11']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_12']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_13']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_14']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctrl24_TC_2']	=	{text =  'Контроль 24 В ТС №2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GPA7_AS_ON']	=	{text =  'ГПА №7 Включить звуковую сигнализацию',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GPA8_AS_ON']	=	{text =  'ГПА №8 Включить звуковую сигнализацию',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GPA9_AS_ON']	=	{text =  'ГПА №9 Включить звуковую сигнализацию',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_15']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_16']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_17']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GPA7_S1Gr']	=	{text =  'ГПА №7 Останов в группе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GPA8_S1Gr']	=	{text =  'ГПА №8 Останов в группе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GPA9_S1Gr']	=	{text =  'ГПА №9 Останов в группе',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_18']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_19']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_20']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_21']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_22']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_23']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_24']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_25']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_26']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_27']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_28']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_29']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_30']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_31']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_32']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_33']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_34']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_35']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_36']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_37']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_38']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_39']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctrl24_TC_3']	=	{text =  'Контроль 24 В ТС №3',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.RU04_ESSN_inc1_Upres']	=	{text =  'РУ-0,4кВ ЭССН. Ввод №1: наличие напряжения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.RU04_ESSN_inc2_Upres']	=	{text =  'РУ-0,4кВ ЭССН. Ввод №2: наличие напряжения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.RU04_ESSN_ASM_B_Upres']	=	{text =  'РУ-0,4кВ ЭССН. Сборные шины: наличие напряжения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AGRS_Tech_FLT']	=	{text =  'Технологическая авария АГРС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AGRS_Door_open']	=	{text =  'Дверь АГРС открыта',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Inc1_LEP3_Ulost']	=	{text =  'Ввод 1 (ЛЭП №3):  отсутствие напряжения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Inc1_LEP3_VMP10_ON']	=	{text =  'Ввод 1 (ЛЭП №3):  ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Inc1_LEP3_VMP10_OFF']	=	{text =  'Ввод 1 (ЛЭП №3):  ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.TR2_TKU_VMP10_ON']	=	{text =  'Трансформатор №2 ТКУ: ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.TR2_TKU_VMP10_OFF']	=	{text =  'Трансформатор №2 ТКУ: ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.LEP_EXZ_Sev_VMP10_ON']	=	{text =  'ЛЭП –ЭХЗ «Север»:  ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.LEP_EXZ_Sev_VMP10_OFF']	=	{text =  'ЛЭП –ЭХЗ «Север»:  ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Inc2_LEP17_Ulost']	=	{text =  'Ввод 2 (ЛЭП №17):  отсутствие напряжения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Inc2_LEP17_VMP10_ON']	=	{text =  'Ввод 2 (ЛЭП №17):  ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Inc2_LEP17_VMP10_OFF']	=	{text =  'Ввод 2 (ЛЭП №17):  ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.TR1_TKU_VMP10_ON']	=	{text =  'Трансформатор №1 ТКУ: ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.TR1_TKU_VMP10_OFF']	=	{text =  'Трансформатор №1 ТКУ: ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.LEP_EXZ_Ug_VMP10_ON']	=	{text =  'ЛЭП –ЭХЗ «Юг»:  ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.LEP_EXZ_Ug_VMP10_OFF']	=	{text =  'ЛЭП –ЭХЗ «Юг»:  ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.MG1_VMP10_ON']	=	{text =  'МГ-№1: ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.MG1_VMP10_OFF']	=	{text =  'МГ-№1: ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.MG2_VMP10_ON']	=	{text =  'МГ-№2: ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.MG2_VMP10_OFF']	=	{text =  'МГ-№2: ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.SS_10KV_VMP10_ON']	=	{text =  'Секционный выключатель 10кВ: ВМП-10 включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.SS_10KV_VMP10_OFF']	=	{text =  'Секционный выключатель 10кВ: ВМП-10 отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_40']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_41']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_42']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_43']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_44']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_45']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctrl24_TC_4']	=	{text =  'Контроль 24 В ТС №4',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctrl_OP_AC220']	=	{text =  'Контроль основного питания ~220 В',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctrl_RP_DC200']	=	{text =  'Контроль резервного питания 220 В пост.',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AP_ON']	=	{text =  'Автоматы питания включены',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.SHKU17_Doors_open']	=	{text =  'Двери ШКУ-17 открыты',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctrl_Isp_Raz']	=	{text =  'Контроль исправности разрядников',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_OIP24DC_IC']	=	{text =  'Неисправность осн. ИП =24 В внутр. цепей',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_RIP24DC_IC']	=	{text =  'Неисправность рез. ИП =24 В внутр. цепей',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_OIP24DC_AI']	=	{text =  'Неисправность осн. ИП =24 В AI',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_RIP24DC_AI']	=	{text =  'Неисправность рез. ИП =24 В AI',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_OIP24DC_DI']	=	{text =  'Неисправность осн. ИП =24 В DI',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_RIP24DC_DI']	=	{text =  'Неисправность рез. ИП =24 В DI',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_OIP24DC_DO']	=	{text =  'Неисправность осн. ИП =24 В DO',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_RIP24DC_DO']	=	{text =  'Неисправность рез. ИП =24 В DO',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_OIP24DC_BEAO']	=	{text =  'Неисправность осн. ИП =24 В БЭАО',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ispr_RIP24DC_BEAO']	=	{text =  'Неисправность рез. ИП =24 В БЭАО',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_46']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.EAO_KC_PU']	=	{text =  'ЭАО КЦ с ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.EAO_KC_PU_KCD']	=	{text =  'ЭАО КЦ с ПУ. Неисправность КЦД',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_KC_PU']	=	{text =  'АО КЦ бс с ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_KC_PU_KCD']	=	{text =  'АО КЦ бс с ПУ. Неисправность КЦД',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_KC_PU']	=	{text =  'АО КЦ сс с ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_KC_PU_KCD']	=	{text =  'АО КЦ сс с ПУ. Неисправность КЦД',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.EAO_KC_PEAO']	=	{text =  'ЭАО КЦ с ПЭАО',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.EAO_KC_PEAO_KCD']	=	{text =  'ЭАО КЦ с ПЭАО. Неисправность КЦД',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ctr_P_KR']	=	{text =  'Контроль питания кранов',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.BEAO_ready']	=	{text =  'Готовность БЭАО',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PU_ready']	=	{text =  'Готовность ПУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ask_sound']	=	{text =  'Съем звука (ПУ)',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.RU_KR']	=	{text =  'РУ кранами',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_47']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_48']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_49']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Neispr_P_SHARM']	=	{text =  'Неисправность питания шкафа АРМ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Pinv_SHARM_pres']	=	{text =  'Наличие пит. ШАРМ от инв.',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AP_SHARM_ON']	=	{text =  'Автоматы пит. ШАРМ включены',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Doors_SHARM_OPEN']	=	{text =  'Двери ШАРМ открыты',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Neispr_P_US']	=	{text =  'Неисправность. пит. устр. серверного',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Ppres_Inv_US']	=	{text =  'Наличие пит. УС от инв.',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AP_US_ON']	=	{text =  'Автоматы пит. УС включены',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Doors_US_OPEN']	=	{text =  'Двери УС открыты',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Neispr_OP_SHSO']	=	{text =  'Неисправность осн. пит. ШСО',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Neispr_RP_SHSO']	=	{text =  'Неисправность рез. пит. ШСО',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AP_SHSO_ON']	=	{text =  'Автоматы пит. ШСО включены',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Doors_SHSO_OPEN']	=	{text =  'Двери ШСО открыты',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_50']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_51']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_52']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_53']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30B_OFF']	=	{text =  'Кран 30Б Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30B_ON']	=	{text =  'Кран 30Б Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30B_IM']	=	{text =  'Кран 30Б Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30B_VK']	=	{text =  'Кран 30Б Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30Bbis_OFF']	=	{text =  'Кран 30Ббис Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30Bbis_ON']	=	{text =  'Кран 30Ббис Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30Bbis_IM']	=	{text =  'Кран 30Ббис Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr30Bbis_VK']	=	{text =  'Кран 30Ббис Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7B_OFF']	=	{text =  'Кран 7Б Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7B_ON']	=	{text =  'Кран 7Б Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7B_IM']	=	{text =  'Кран 7Б Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7B_VK']	=	{text =  'Кран 7Б Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7Bzak_OFF']	=	{text =  'Кран 7Б зак Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7Bzak_ON']	=	{text =  'Кран 7Б зак Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7Bzak_IM']	=	{text =  'Кран 7Б зак Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr7Bzak_VK']	=	{text =  'Кран 7Б зак Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8B_OFF']	=	{text =  'Кран 8Б Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8B_ON']	=	{text =  'Кран 8Б Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8B_IM']	=	{text =  'Кран 8Б Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8B_VK']	=	{text =  'Кран 8Б Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8Bbis_OFF']	=	{text =  'Кран 8Ббис Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8Bbis_ON']	=	{text =  'Кран 8Ббис Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8Bbis_IM']	=	{text =  'Кран 8Ббис Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr8Bbis_VK']	=	{text =  'Кран 8Ббис Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_55']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_56']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_57']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_58']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_59']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_60']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_61']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_62']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr17B_OFF']	=	{text =  'Кран 17Б Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr17B_ON']	=	{text =  'Кран 17Б Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr17B_IM']	=	{text =  'Кран 17Б Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr17B_VK']	=	{text =  'Кран 17Б Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr18B_OFF']	=	{text =  'Кран 18Б Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr18B_ON']	=	{text =  'Кран 18Б Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr18B_IM']	=	{text =  'Кран 18Б Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr18B_VK']	=	{text =  'Кран 18Б Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_63']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_64']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_65']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.rez_66']	=	{text =  'Резерв',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr6B_OFF']	=	{text =  'Кран 6Б Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr6B_ON']	=	{text =  'Кран 6Б Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr6B_IM']	=	{text =  'Кран 6Б Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.kr6B_VK']	=	{text =  'Кран 6Б Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6BR_OFF']	=	{text =  'Кран 6БР Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6BR_ON']	=	{text =  'Кран 6БР Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6BR_IM']	=	{text =  'Кран 6БР Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6BR_VK']	=	{text =  'Кран 6БР Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krA_OFF']	=	{text =  'Кран А Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krA_ON']	=	{text =  'Кран А Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krA_IM']	=	{text =  'Кран А Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krA_VK']	=	{text =  'Кран А Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krC_OFF']	=	{text =  'Кран С Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krC_ON']	=	{text =  'Кран С Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krC_IM']	=	{text =  'Кран С Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.krC_VK']	=	{text =  'Кран С Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6_9_OFF']	=	{text =  'Кран 6-9 Закрыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6_9_ON']	=	{text =  'Кран 6-9 Открыт',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6_9_IM']	=	{text =  'Кран 6-9 Контроль цепи ИМ - неисправность',		src = source_aps.e, class = event_aps.w},
['SHKU17_A5_APS.kr6_9_VK']	=	{text =  'Кран 6-9 Контроль цепи ВК - неисправность',		src = source_aps.e, class = event_aps.w},

--АПС кранов и др. ИМ
['SHKU17_A3_APS.Heat_APK_non']	=	{text =  'Обогрев АПК - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_noff']	=	{text =  'Обогрев АПК - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_nstart']	=	{text =  'Обогрев АПК - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_selfon']	=	{text =  'Обогрев АПК - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_selfoff']	=	{text =  'Обогрев АПК - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_flt']	=	{text =  'Обогрев АПК - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_ncon']	=	{text =  'Обогрев АПК - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Heat_APK_ncoff']	=	{text =  'Обогрев АПК - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_non']	=	{text =  'Насос РЗ-30 ГСМ - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_noff']	=	{text =  'Насос РЗ-30 ГСМ - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_nstart']	=	{text =  'Насос РЗ-30 ГСМ - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_selfon']	=	{text =  'Насос РЗ-30 ГСМ - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_selfoff']	=	{text =  'Насос РЗ-30 ГСМ - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_flt']	=	{text =  'Насос РЗ-30 ГСМ - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_ncon']	=	{text =  'Насос РЗ-30 ГСМ - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.P3_30_ncoff']	=	{text =  'Насос РЗ-30 ГСМ - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_non']	=	{text =  'Периметральное освещение КЦ 2 - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_noff']	=	{text =  'Периметральное освещение КЦ 2 - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_nstart']	=	{text =  'Периметральное освещение КЦ 2 - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_selfon']	=	{text =  'Периметральное освещение КЦ 2 - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_selfoff']	=	{text =  'Периметральное освещение КЦ 2 - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_flt']	=	{text =  'Периметральное освещение КЦ 2 - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_ncon']	=	{text =  'Периметральное освещение КЦ 2 - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PL_KC2_ncoff']	=	{text =  'Периметральное освещение КЦ 2 - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_non']	=	{text =  'Кран 30Б - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_noff']	=	{text =  'Кран 30Б - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_nstart']	=	{text =  'Кран 30Б - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_selfon']	=	{text =  'Кран 30Б - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_selfoff']	=	{text =  'Кран 30Б - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_flt']	=	{text =  'Кран 30Б - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_ncon']	=	{text =  'Кран 30Б - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30B_ncoff']	=	{text =  'Кран 30Б - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_non']	=	{text =  'Кран  30Б бис - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_noff']	=	{text =  'Кран  30Б бис - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_nstart']	=	{text =  'Кран  30Б бис - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_selfon']	=	{text =  'Кран  30Б бис - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_selfoff']	=	{text =  'Кран  30Б бис - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_flt']	=	{text =  'Кран  30Б бис - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_ncon']	=	{text =  'Кран  30Б бис - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR30Bbis_ncoff']	=	{text =  'Кран  30Б бис - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_non']	=	{text =  'Кран 7Б - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_noff']	=	{text =  'Кран 7Б - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_nstart']	=	{text =  'Кран 7Б - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_selfon']	=	{text =  'Кран 7Б - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_selfoff']	=	{text =  'Кран 7Б - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_flt']	=	{text =  'Кран 7Б - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_ncon']	=	{text =  'Кран 7Б - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7B_ncoff']	=	{text =  'Кран 7Б - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_non']	=	{text =  'Кран 7Б зак - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_noff']	=	{text =  'Кран 7Б зак - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_nstart']	=	{text =  'Кран 7Б зак - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_selfon']	=	{text =  'Кран 7Б зак - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_selfoff']	=	{text =  'Кран 7Б зак - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_flt']	=	{text =  'Кран 7Б зак - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_ncon']	=	{text =  'Кран 7Б зак - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR7zak_ncoff']	=	{text =  'Кран 7Б зак - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_non']	=	{text =  'Кран 8Б - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_noff']	=	{text =  'Кран 8Б - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_nstart']	=	{text =  'Кран 8Б - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_selfon']	=	{text =  'Кран 8Б - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_selfoff']	=	{text =  'Кран 8Б - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_flt']	=	{text =  'Кран 8Б - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_ncon']	=	{text =  'Кран 8Б - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8B_ncoff']	=	{text =  'Кран 8Б - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_non']	=	{text =  'Кран 8Б бис - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_noff']	=	{text =  'Кран 8Б бис - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_nstart']	=	{text =  'Кран 8Б бис - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_selfon']	=	{text =  'Кран 8Б бис - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_selfoff']	=	{text =  'Кран 8Б бис - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_flt']	=	{text =  'Кран 8Б бис - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_ncon']	=	{text =  'Кран 8Б бис - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR8Bbis_ncoff']	=	{text =  'Кран 8Б бис - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_non']	=	{text =  'Кран  17Б - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_noff']	=	{text =  'Кран  17Б - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_nstart']	=	{text =  'Кран  17Б - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_selfon']	=	{text =  'Кран  17Б - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_selfoff']	=	{text =  'Кран  17Б - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_flt']	=	{text =  'Кран  17Б - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_ncon']	=	{text =  'Кран  17Б - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR17B_ncoff']	=	{text =  'Кран  17Б - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_non']	=	{text =  'Кран 18Б - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_noff']	=	{text =  'Кран 18Б - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_nstart']	=	{text =  'Кран 18Б - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_selfon']	=	{text =  'Кран 18Б - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_selfoff']	=	{text =  'Кран 18Б - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_flt']	=	{text =  'Кран 18Б - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_ncon']	=	{text =  'Кран 18Б - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR18B_ncoff']	=	{text =  'Кран 18Б - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_non']	=	{text =  'Кран 6Б - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_noff']	=	{text =  'Кран 6Б - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_nstart']	=	{text =  'Кран 6Б - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_selfon']	=	{text =  'Кран 6Б - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_selfoff']	=	{text =  'Кран 6Б - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_flt']	=	{text =  'Кран 6Б - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_ncon']	=	{text =  'Кран 6Б - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6B_ncoff']	=	{text =  'Кран 6Б - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_non']	=	{text =  'Кран 6БР - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_noff']	=	{text =  'Кран 6БР - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_nstart']	=	{text =  'Кран 6БР - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_selfon']	=	{text =  'Кран 6БР - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_selfoff']	=	{text =  'Кран 6БР - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_flt']	=	{text =  'Кран 6БР - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_ncon']	=	{text =  'Кран 6БР - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6BR_ncoff']	=	{text =  'Кран 6БР - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_non']	=	{text =  'Кран А - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_noff']	=	{text =  'Кран А - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_nstart']	=	{text =  'Кран А - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_selfon']	=	{text =  'Кран А - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_selfoff']	=	{text =  'Кран А - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_flt']	=	{text =  'Кран А - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_ncon']	=	{text =  'Кран А - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRA_ncoff']	=	{text =  'Кран А - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_non']	=	{text =  'Кран С - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_noff']	=	{text =  'Кран С - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_nstart']	=	{text =  'Кран С - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_selfon']	=	{text =  'Кран С - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_selfoff']	=	{text =  'Кран С - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_flt']	=	{text =  'Кран С - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_ncon']	=	{text =  'Кран С - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KRC_ncoff']	=	{text =  'Кран С - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_non']	=	{text =  'Кран 6-9 - не открыт/не включен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_noff']	=	{text =  'Кран 6-9 - не закрыт/не отключен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_nstart']	=	{text =  'Кран 6-9 - не стронулся',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_selfon']	=	{text =  'Кран 6-9 - самопроизвольное открытие/включение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_selfoff']	=	{text =  'Кран 6-9 - самопроизвольное закрытие/отключение',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_flt']	=	{text =  'Кран 6-9 - ошибка концевиков',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_ncon']	=	{text =  'Кран 6-9 - КЦУ открытия/включения',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KR6_9_ncoff']	=	{text =  'Кран 6-9 - КЦУ закрытия/отключения',		src = source_aps.e, class = event_aps.w},

--АПС из алгоритмов
['SHKU17_A1_APS.Pg2plum_over_PS']	=	{text =  'Давление газа на выходном шлейфе высокое',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Pg2plum_over_AS']	=	{text =  'Давление газа на выходном шлейфе аварийно высокое',		src = source_aps.e, class = event_aps.a},
['SHKU17_A1_APS.Tozh_H_PS']	=	{text =  'Температура охлаждающей жидкости - высокая',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ttg_L_PS']	=	{text =  'Температура топливного газа низкая',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ttg_H_PS']	=	{text =  'Температура топливного газа высокая',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ptg_L_PS']	=	{text =  'Давление топливного  газа низкое',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.Ptg_H_PS']	=	{text =  'Давление топливного  газа высокое',		src = source_aps.e, class = event_aps.w},

--АПС системные
['SHKU17_A1_APS.PRU_Link_flt']	=	{text =  'Ошибка связи с РПКУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.PRU_btn_AOS']	=	{text =  'Нажата кнопка АОсс на РПКУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.PRU_btn_AOB']	=	{text =  'Нажата кнопка АОбс на РПКУ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A1_APS.PRU_btn_NO']	=	{text =  'Нажата кнопка НО на РПКУ',		src = source_aps.e, class = event_aps.w},

['SHKU17_A3_APS.ARM_btn_AOS']	=	{text =  'Нажата кнопка АОсс на АРМ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.ARM_btn_AOB']	=	{text =  'Нажата кнопка АОбс на АРМ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.ARM_btn_NO']	=	{text =  'Нажата кнопка НО на АРМ',		src = source_aps.e, class = event_aps.w},

['SHKU17_A3_APS.dP1KR30B_hi']	=	{text =  'Высокий перепад давления на кр30б',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.dP1KR30Bbis_hi']	=	{text =  'Высокий перепад давления на кр30б бис',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.MD_KC_AOB']	=	{text =  'Выполняется АО без стравливания',		src = source_aps.e, class = event_aps.a},
['SHKU17_A3_APS.MD_KC_AOS']	=	{text =  'Выполняется АО со стравливанием',		src = source_aps.e, class = event_aps.a},
['SHKU17_A3_APS.MD_KC_NO']	=	{text =  'Выполняется НО без стравливания',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_DONE']	=	{text =  'АОбс завершен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_DONE_INCORRECT']	=	{text =  'АОбс завершен некорректно',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_DONE']	=	{text =  'АОсс завершен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_DONE_INCORRECT']	=	{text =  'АОсс завершен некорректно',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.NO_DONE']	=	{text =  'НО завершен',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.NO_DONE_INCORRECT']	=	{text =  'НО завершен некорректно',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GR1_KOL']	=	{text =  'Группа 1 Кольцо',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GR2_KOL']	=	{text =  'Группа 2 Кольцо',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GR1_MAG']	=	{text =  'Группа 1 Магистраль',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.GR2_MAG']	=	{text =  'Группа 2 Магистраль',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.KC_EAO']	=	{text =  'Выполняется ЭАО',		src = source_aps.e, class = event_aps.a},
['SHKU17_A3_APS.AOB_kr30B_open']	=	{text =  'Запрос на открытие крана 30б при АОБ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_kr30Bbis_open']	=	{text =  'Запрос на открытие крана 30б бис при АОБ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_kr30B_open']	=	{text =  'Запрос на открытие крана 30б при АОС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_kr30Bbis_open']	=	{text =  'Запрос на открытие крана 30б бис при АОС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_kr30B_open_accept']	=	{text =  'Подтверждение оператором открытия окна управления краном 30б при АОБ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_kr30B_open_not_accept']	=	{text =  'Отмена от оператора открытия окна управления краном 30б при АОБ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_kr30Bbis_open_accept']	=	{text =  'Подтверждение оператором открытия окна управления краном 30б бис при АОБ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_kr30Bbis_open_not_accept']	=	{text =  'Отмена от оператора открытия окна управления краном 30б бис при АОБ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_kr30B_open_accept']	=	{text =  'Подтверждение оператором открытия окна управления краном 30б при АОС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_kr30B_open_not_accept']	=	{text =  'Отмена от оператора открытия окна управления краном 30б при АОС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_kr30Bbis_open_accept']	=	{text =  'Подтверждение оператором открытия окна управления краном 30б бис при АОС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOS_kr30Bbis_open_not_accept']	=	{text =  'Отмена от оператора открытия окна управления краном 30б бис при АОС',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AO_In_Group1']	=	{text =  'АО в группе 1',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AO_In_Group2']	=	{text =  'АО в группе 2',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Tg_hi2KC']	=	{text =  'Высокая температура газа на выходе КЦ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Tg_ala_hi2KC']	=	{text =  'Аварийно высокая температура газа на выходе КЦ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Tg_ala_hi2KC_delay']	=	{text =  'Аварийно высокая температура газа на выходе КЦ',		src = source_aps.e, class = event_aps.a},
['SHKU17_A3_APS.Pg_hi2KC']	=	{text =  'Высокое давление газа на выходе КЦ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Pg_ala_hi2KC']	=	{text =  'Аварийно высокое давление газа на выходе КЦ',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.Pg_ala_hi2KC_delay']	=	{text =  'Аварийно высокое давление газа на выходе КЦ',		src = source_aps.e, class = event_aps.a},
['SHKU17_A3_APS.OPG_KR_ON']	=	{text =  'Команда на открытие кранов 6б 6бр от АСУТП',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.AOB_ASUTP_CMD']	=	{text =  'Команда АОБ от АСУТП',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PPU_FIRE']	=	{text =  'Проверка предпусковых условий: Пожар',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PPU_ZAG']	=	{text =  'Проверка предпусковых условий: Загазованность 20%',		src = source_aps.e, class = event_aps.w},
['SHKU17_A3_APS.PPU_RDY_TO_START']	=	{text =  'Проверка предпусковых условий: Есть готовность к пуску',		src = source_aps.e, class = event_aps.w},
}



while true do
    local Core_value
    for w,_ in pairs(signals) do     --Цикл по ключам таблицы signals
		Core_value = Core[w]
        if (oldsignal[w] and not Core_value) and (signals[w].class ~= 102) or (not oldsignal[w] or oldsignal[w] == nil) and Core_value then Add_Event({w,Core_value}) end
        oldsignal[w] = Core_value
    end
os.sleep(0.1)
end